---
- name: Deploy
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Install requirements
      delegate_to: localhost
      ansible.builtin.command: ansible-galaxy install -r {{ role_path }}/requirements.yml
...