---
- name: Create Secrets in Secretsmanager
  hosts: localhost
  gather_facts: true
  vars:
    super_secret_string: "secret-string"

  tasks:
    - name: Configure AWS CLI
      set_fact:
        aws_access_key: "test"
        aws_secret_key: "test"
        aws_region: "eu-central-1"
    
    - name: Add string to AWS Secrets Manager
      community.aws.aws_secret:
        name: "TestSecret"
        state: present
        secret_type: "string"
        secret: "{{ super_secret_string }}"
        endpoint_url: "http://localhost:4566"
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"
...